// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSense.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniSense.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110203112_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniSense.Domain.Entities.DataStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MeasurementUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("SensorDeviceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("SensorDeviceId");

                    b.ToTable("DataStreams");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Celsius",
                            Symbol = "°C"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Megagram per cubic metre",
                            Symbol = "mg/m³"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hectopascal",
                            Symbol = "hPa"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lux",
                            Symbol = "lux"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Percent",
                            Symbol = "%"
                        });
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataStreamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DataStreamId", "Timestamp");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.SensorDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("SensorDevices");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.DataStream", b =>
                {
                    b.HasOne("MiniSense.Domain.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany("Streams")
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiniSense.Domain.Entities.SensorDevice", "SensorDevice")
                        .WithMany("Streams")
                        .HasForeignKey("SensorDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");

                    b.Navigation("SensorDevice");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.SensorData", b =>
                {
                    b.HasOne("MiniSense.Domain.Entities.DataStream", "DataStream")
                        .WithMany("Measurements")
                        .HasForeignKey("DataStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataStream");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.SensorDevice", b =>
                {
                    b.HasOne("MiniSense.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.DataStream", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.SensorDevice", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("MiniSense.Domain.Entities.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
